DATASET:
  NAME: "LJSpeech"
  TRAIN:
    MEL_SCP: ""
    VARIANCE_SCP: ""
    JSON_DATA: ""
  VAL:
    MEL_SCP: ""
    VARIANCE_SCP: ""
    JSON_DATA: ""

TEXT:
  CLEANER: ["english_cleaners"]

AUDIO:
  SAMPLING_RATE: 22050
  FILTER_LENGTH: 1024
  HOP_LENGTH: 256
  WIN_LENGTH: 1024
  MAX_WAV_VALUE: 32768.0
  N_MEL_CHANNELS: 80
  MEL_FMIN: 0.0
  MEL_FMAX: 8000.0

CONST:
  PAD: 0
  UNK: 1
  BOS: 2
  EOS: 3
  PAD_WORD: "<blank>"
  UNK_WORD: "<unk>"
  BOS_WORD: "<s>"
  EOS_WORD: "</s>"

MODEL:
  ENCODER:
    LAYER: 4
    HEAD: 2
    HIDDEN: 256
    DROPOUT: 0.2
  DECODER:
    LAYER: 4
    HEAD: 2
    HIDDEN: 256
    DROPOUT: 0.2
  FFT:
    CONV1D_FILTER_SIZE: 1024
    CONV1D_KERNEL_SIZE: [9, 1]
  VARIANCE_PREDICTOR:
    FILTER_SIZE: 256
    KERNEL_SIZE: 3
    DROPOUT: 0.3
  # optional
  POSTNET:
    EMBEDDING_DIM: 512
    KERNEL_SIZE: 5
    N_CONVOLUTIONS: 5

  MAX_SEQ_LEN: 1000
  N_SRC_VOCAB: -1

QUANTIZATION:
  F0_MIN: 71.0
  F0_MAX: 795.8
  ENERGY_MIN: 0.0
  ENERGY_MAX: 315.0
  N_BINS: 256
  LOG_OFFSET: 1.0

OPT:
  BATCH_SIZE: 16
  EPOCH: 1000
  N_WARM_UP_STEP: 4000
  GRAD_CLIP_THRESH: 1.0
  ACCUM_STEPS: 1
  BETAS: [0.9, 0.98]
  EPS: 1e-9
  WEIGHT_DECAY: 0.0
  RESTORE_STEP: 0

VOCODER: "melgan"

DIR_PATH:
  CKPT: ""
  SYNTHESIS: ""
  EVAL: ""
  LOG: ""
  TEST: ""

LOGGING:
  SAVE_STEP: 10000
  SYNTH_STEP: 1000
  EVAL_STEP: 1000
  EVAL_SIZE: 256
  LOG_STEP: 1000
  CLEAR_TIME: 20
